
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mkrvidor(
	// system signals
	input         iCLK,
	input         iRESETn,
	input         iSAM_INT,
	output        oSAM_INT,
	
	// SDRAM
	output        oSDRAM_CLK,
	output [11:0] oSDRAM_ADDR,
	output [1:0]  oSDRAM_BA,
	output        oSDRAM_CASn,
	output        oSDRAM_CKE,
	output        oSDRAM_CSn,
	inout  [15:0] bSDRAM_DQ,
	output [1:0]  oSDRAM_DQM,
	output        oSDRAM_RASn,
	output        oSDRAM_WEn,

	// SAM D21 PINS
	inout         bMKR_AREF,
	inout  [6:0]  bMKR_A,
	inout  [14:0] bMKR_D,
	
	// Mini PCIe
	inout         bPEX_RST,
	inout         bPEX_PIN6,
	inout         bPEX_PIN8,
	inout         bPEX_PIN10,
	input         iPEX_PIN11,
	inout         bPEX_PIN12,
	input         iPEX_PIN13,
	inout         bPEX_PIN14,
	inout         bPEX_PIN16,
	inout         bPEX_PIN20,
	input         iPEX_PIN23,
	input         iPEX_PIN25,
	inout         bPEX_PIN28,
	inout         bPEX_PIN30,
	input         iPEX_PIN31,
	inout         bPEX_PIN32,
	input         iPEX_PIN33,
	inout         bPEX_PIN42,
	inout         bPEX_PIN44,
	inout         bPEX_PIN45,
	inout         bPEX_PIN46,
	inout         bPEX_PIN47,
	inout         bPEX_PIN48,
	inout         bPEX_PIN49,
	inout         bPEX_PIN51,

	// NINA interface
	inout         bWM_PIO1,
	inout         bWM_PIO2,
	inout         bWM_PIO3,
	inout         bWM_PIO4,
	inout         bWM_PIO5,
	inout         bWM_PIO7,
	inout         bWM_PIO8,
	inout         bWM_PIO18,
	inout         bWM_PIO20,
	inout         bWM_PIO21,
	inout         bWM_PIO27,
	inout         bWM_PIO28,
	inout         bWM_PIO29,
	inout         bWM_PIO31,
	input         iWM_PIO32,
	inout         bWM_PIO34,
	inout         bWM_PIO35,
	inout         bWM_PIO36,
	input         iWM_TX,
	inout         oWM_RX,
	inout         oWM_RESET,

	// HDMI output
	output [2:0]  oHDMI_TX,
	output        oHDMI_CLK,

	inout         bHDMI_SDA,
	inout         bHDMI_SCL,
	
	input         iHDMI_HPD,
	
	// MIPI input
	input  [1:0]  iMIPI_D,
	input         iMIPI_CLK,
	inout         bMIPI_SDA,
	inout         bMIPI_SCL,
	inout  [1:0]  bMIPI_GP,

	// Q-SPI Flash interface
	output        oFLASH_SCK,
	output        oFLASH_CS,
	inout         oFLASH_MOSI,
	inout         iFLASH_MISO,
	inout         oFLASH_HOLD,
	inout         oFLASH_WP
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
	wire scl_pad_i;
	wire scl_pad_o;
	wire scl_padoen_o;
	wire sda_pad_i;
	wire sda_pad_o;
	wire sda_padoen_o;

	wire [14:0] address_a_sig;
	wire [14:0] address_b_sig;
	wire [3:0] byteena_a_sig;
	wire [3:0] byteena_b_sig;
	wire  clock_a_sig;
	wire  clock_b_sig;
	wire [31:0] data_a_sig;
	wire [31:0] data_b_sig;
	wire  enable_a_sig;
	wire  enable_b_sig;
	wire  wren_a_sig;
	wire  wren_b_sig;
	wire [31:0] q_a_sig;
	wire [31:0] q_b_sig;
	wire	[31:0]  q_boot_sig;
//=======================================================
//  Structural coding
//=======================================================
	wire CLOCK_25;

	pll	pll_25_inst (
		.areset ( 1'b0 ),
		.inclk0 ( iCLK ),
		.c0 ( CLOCK_25 ),
		.locked ( )
		);
		


	//make boot memory and keep feeding it address_a_sig
	//if boot memory select boot memory readdata
	reg [31:0] cnt = 0;
	wire rst;
	always@(posedge CLOCK_25)
	begin
	if(cnt < 32'd25000000)
		cnt <= cnt+1;
	end
	assign rst = cnt < 32'd25000000;

	mem mem_inst
	(
		.address_a(address_a_sig) ,	// input [14:0] address_a_sig
		.address_b({4'b1000,address_b_sig[10:0]}) ,	// input [14:0] address_b_sig
		.byteena_a(byteena_a_sig) ,	// input [3:0] byteena_a_sig
		.byteena_b(byteena_b_sig) ,	// input [3:0] byteena_b_sig
		.clock_a(clock_a_sig) ,	// input  clock_a_sig
		.clock_b(clock_b_sig) ,	// input  clock_b_sig
		.data_a(data_a_sig) ,	// input [31:0] data_a_sig
		.data_b(data_b_sig) ,	// input [31:0] data_b_sig
		.enable_a(enable_a_sig) ,	// input  enable_a_sig
		.enable_b(enable_b_sig) ,	// input  enable_b_sig
		.wren_a(wren_a_sig) ,	// input  wren_a_sig
		.wren_b(wren_b_sig) ,	// input  wren_b_sig
		.q_a(q_a_sig) ,	// output [31:0] q_a_sig
		.q_b(q_b_sig) 	// output [31:0] q_b_sig
	);

	bootmem	bootmem_inst (
		.address ( address_a_sig ),
		.clken ( enable_a_sig ),
		.clock ( clock_a_sig ),
		.q ( q_boot_sig )
	);

/*
	vga_adapter VGA(
			.resetn(KEY[0]),
			.clock(MAX10_CLK1_50),
			.colour(num[2:0]),
			.x(num[10:3]),
			.y(num[17:11]),
			.plot(num[18]),
			.VGA_R(VGA_R),
			.VGA_G(VGA_G),
			.VGA_B(VGA_B),
			.VGA_HS(VGA_HS),
			.VGA_VS(VGA_VS),
			.VGA_BLANK(VGA_BLANK_N),
			.VGA_SYNC(VGA_SYNC_N),
			.VGA_CLK(VGA_CLK));
		defparam VGA.RESOLUTION = "160x120";
		defparam VGA.MONOCHROME = "FALSE";
		defparam VGA.BITS_PER_COLOUR_CHANNEL = 1;
		defparam VGA.BACKGROUND_IMAGE = "image.colour.mif";
*/	
		
	soc_top soc_top_inst
	(
		.clk_i	(CLOCK_25) ,	// input  clk_i_sig
		.reset_i(~iRESETn | rst) ,	// input  reset_i_sig
		//imem
		.address_a_o(address_a_sig) ,	// output [14:0] address_a_sig
		.address_b_o(address_b_sig) ,	// output [14:0] address_b_sig
		.byteena_a_o(byteena_a_sig) ,	// output [3:0] byteena_a_sig
		.byteena_b_o(byteena_b_sig) ,	// output [3:0] byteena_b_sig
		.clock_a_o	(clock_a_sig) ,	// output  clock_a_sig
		.clock_b_o	(clock_b_sig) ,	// output  clock_b_sig
		.data_a_o	(data_a_sig) ,	// output [31:0] data_a_sig
		.data_b_o	(data_b_sig) ,	// output [31:0] data_b_sig
		.enable_a_o	(enable_a_sig) ,	// output  enable_a_sig
		.enable_b_o	(enable_b_sig) ,	// output  enable_b_sig
		.wren_a_o	(wren_a_sig) ,	// output  wren_a_sig
		.wren_b_o	(wren_b_sig) ,	// output  wren_b_sig
		.q_a_i		(q_a_sig) ,	// input [31:0] q_a_sig
		.q_b_i		(q_b_sig) ,	// input [31:0] q_b_sig
    	.q_boot_i	(q_boot_sig),

		//uart
		.tx_o	(iPEX_PIN11) ,	// output  tx_sig
		.rx_i	(bPEX_PIN42) ,	// input  rx_sig
		// spi
		.mosi_o        (),
		.miso_i        (),
		.SCK_o         (),
		.slave_select_o(),
		//i2c

		.scl_pad_i		(scl_pad_i),
		.scl_pad_o		(scl_pad_o),
		.scl_padoen_o	(scl_padoen_o),
		.sda_pad_i		(sda_pad_i),
		.sda_pad_o		(sda_pad_o),
		.sda_padoen_o	(sda_padoen_o),
		
		//gpio
		.gpio_oen	(),
		.gpio_o		({bPEX_PIN8,bPEX_PIN10,bPEX_PIN12,bPEX_PIN14,bPEX_PIN16,bPEX_PIN20,bPEX_PIN28,bPEX_PIN30,}),
		.gpio_i		(),
		//pwm
		.pwm1_h_o   (),
		.pwm1_l_o   (),
		.pwm2_h_o	(),
		.pwm2_l_o	(),
		
		// jtag
		.tck_i(),	// input  TCK_sig
		.tms_i(),	// input  TMS_sig
		.tdi_i(),	// input  TDI_sig
		.tdo_o()	// output TDO_sig
	);

endmodule
