onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_soc_top/soc_top_inst/clk_i
add wave -noupdate /tb_soc_top/soc_top_inst/reset_i
add wave -noupdate /tb_soc_top/soc_top_inst/address_a_o
add wave -noupdate /tb_soc_top/soc_top_inst/address_b_o
add wave -noupdate /tb_soc_top/soc_top_inst/byteena_a_o
add wave -noupdate /tb_soc_top/soc_top_inst/byteena_b_o
add wave -noupdate /tb_soc_top/soc_top_inst/clock_a_o
add wave -noupdate /tb_soc_top/soc_top_inst/clock_b_o
add wave -noupdate /tb_soc_top/soc_top_inst/data_a_o
add wave -noupdate /tb_soc_top/soc_top_inst/data_b_o
add wave -noupdate /tb_soc_top/soc_top_inst/enable_a_o
add wave -noupdate /tb_soc_top/soc_top_inst/enable_b_o
add wave -noupdate /tb_soc_top/soc_top_inst/wren_a_o
add wave -noupdate /tb_soc_top/soc_top_inst/wren_b_o
add wave -noupdate /tb_soc_top/soc_top_inst/q_a_i
add wave -noupdate /tb_soc_top/soc_top_inst/q_b_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_oen
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_o
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_i
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/pc_sel
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/pc_in
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/pc_out
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/pc_id
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/branch_taken
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/ctrl_bus_if_id
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/ctrl_bus_ie
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/ctrl_bus_imem
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/ctrl_bus_iwb
add wave -noupdate /tb_soc_top/soc_top_inst/core_top_inst/instruction_pipe
add wave -noupdate -divider Timer
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/clk_i
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/reset
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/stall_i
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/write
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/read
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/chipselect
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/writedata
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/address
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/readdata
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/intr_o
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/prescaler
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/count
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/compare
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/control_r
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/status_r
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/en
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/clock_en
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/clcok_div_count_complete
add wave -noupdate /tb_soc_top/soc_top_inst/timer_inst/clock_divider
add wave -noupdate -divider GPIO
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/clk_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/resetn_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/write_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/read_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/chipselect_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/writedata_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/address_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/readdata_o
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/interrupt_reg
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/gpio_oen
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/gpio_o
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/gpio_i
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/DDR
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/Dout
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/Din
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/cmd
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/in
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/temp_in
add wave -noupdate /tb_soc_top/soc_top_inst/gpio_inst/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6730000 ps} 0} {{Cursor 2} {501890000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 351
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {501869916 ps} {502075958 ps}
