// AUTO-GENERATED by scripts/gen_mem_map.py — DO NOT EDIT
// Source: design/common/mem_map.json


#ifndef NTINY_MEM_MAP_H
#define NTINY_MEM_MAP_H

#define NTINY_RAM_BASE       0x80000000
#define NTINY_RAM_SIZE_BYTES  0x00008000
#define NTINY_BOOT_BASE       0x00001000
#define NTINY_BOOT_SIZE_BYTES  0x00001000

// Peripherals
#define NTINY_UART_BASE      0x10000000
#define NTINY_SPI_BASE      0x10010000
#define NTINY_I2C_BASE      0x10020000
#define NTINY_GPIO_BASE      0x10030000
#define NTINY_PWM_BASE      0x10040000
#define NTINY_TIMER_BASE      0x10050000
#define NTINY_CRC_BASE      0x10060000
#define NTINY_CLINT_BASE      0x02000000
#define NTINY_PLIC_BASE      0x0C000000

// Special
#define NTINY_SOFT_INT_ADDR   0x10070000
#define NTINY_TOHOST_ADDR   0x0F000000

// Backward-compatible aliases
#ifndef UART_BASE_ADDR
  #define UART_BASE_ADDR  NTINY_UART_BASE
#endif
#ifndef TIMER_BASE_ADDR
  #define TIMER_BASE_ADDR  NTINY_TIMER_BASE
#endif
#ifndef GPIO_BASE_ADDR
  #define GPIO_BASE_ADDR  NTINY_GPIO_BASE
#endif
#ifndef PLIC_BASE_ADDR
  #define PLIC_BASE_ADDR  NTINY_PLIC_BASE
#endif
#ifndef SPI_BASE_ADDR
  #define SPI_BASE_ADDR  NTINY_SPI_BASE
#endif
#ifndef BASE_ADDR
  #define BASE_ADDR  NTINY_I2C_BASE
#endif
#ifndef pwm_base_addr
  #define pwm_base_addr  NTINY_PWM_BASE
#endif

#endif // NTINY_MEM_MAP_H
