// AUTO-GENERATED by scripts/gen_mem_map.py — DO NOT EDIT
// Source: design/common/mem_map.json


#ifndef NTINY_MEM_MAP_H
#define NTINY_MEM_MAP_H

#define NTINY_IMEM_BASE       0x00000000
#define NTINY_IMEM_SIZE_BYTES  0x00008000
#define NTINY_DMEM_BASE       0x00010000
#define NTINY_DMEM_SIZE_BYTES  0x00002000
#define NTINY_BOOT_BASE       0x80000000
#define NTINY_BOOT_SIZE_BYTES  0x00000200

// Peripherals
#define NTINY_CRC_BASE      0x00080000
#define NTINY_UART_BASE      0x00100000
#define NTINY_TIMER_BASE      0x00200000
#define NTINY_GPIO_BASE      0x00400000
#define NTINY_PLIC_BASE      0x00800000
#define NTINY_SPI_BASE      0x01000000
#define NTINY_I2C_BASE      0x02000000
#define NTINY_PWM_BASE      0x02001000

// Special
#define NTINY_SOFT_INT_ADDR   0x04000000
#define NTINY_TOHOST_ADDR   0x0F000000

// Backward-compatible aliases
#ifndef UART_BASE_ADDR
  #define UART_BASE_ADDR  NTINY_UART_BASE
#endif
#ifndef TIMER_BASE_ADDR
  #define TIMER_BASE_ADDR  NTINY_TIMER_BASE
#endif
#ifndef GPIO_BASE_ADDR
  #define GPIO_BASE_ADDR  NTINY_GPIO_BASE
#endif
#ifndef PLIC_BASE_ADDR
  #define PLIC_BASE_ADDR  NTINY_PLIC_BASE
#endif
#ifndef SPI_BASE_ADDR
  #define SPI_BASE_ADDR  NTINY_SPI_BASE
#endif
#ifndef BASE_ADDR
  #define BASE_ADDR  NTINY_I2C_BASE
#endif
#ifndef pwm_base_addr
  #define pwm_base_addr  NTINY_PWM_BASE
#endif

#endif // NTINY_MEM_MAP_H
