###############################################################
#  Generated by:      Cadence Innovus 20.13-s083_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Mon Mar 27 16:31:46 2023
#  Design:            top
#  Command:           saveFPlan ../config/top.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 1000.0000 1000.0000
IO Box: 158.2000 158.2000 841.8000 841.8000
Core Box: 178.2000 178.2000 821.8000 822.6000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_357 core 178.2000 820.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_356 core 178.2000 819.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_355 core 178.2000 817.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_354 core 178.2000 815.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_353 core 178.2000 813.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_352 core 178.2000 811.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_351 core 178.2000 810.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_350 core 178.2000 808.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_349 core 178.2000 806.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_348 core 178.2000 804.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_347 core 178.2000 802.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_346 core 178.2000 801.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_345 core 178.2000 799.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_344 core 178.2000 797.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_343 core 178.2000 795.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_342 core 178.2000 793.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_341 core 178.2000 792.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_340 core 178.2000 790.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_339 core 178.2000 788.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_338 core 178.2000 786.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_337 core 178.2000 784.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_336 core 178.2000 783.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_335 core 178.2000 781.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_334 core 178.2000 779.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_333 core 178.2000 777.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_332 core 178.2000 775.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_331 core 178.2000 774.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_330 core 178.2000 772.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_329 core 178.2000 770.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_328 core 178.2000 768.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_327 core 178.2000 766.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_326 core 178.2000 765.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_325 core 178.2000 763.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_324 core 178.2000 761.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_323 core 178.2000 759.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_322 core 178.2000 757.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_321 core 178.2000 756.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_320 core 178.2000 754.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_319 core 178.2000 752.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_318 core 178.2000 750.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_317 core 178.2000 748.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_316 core 178.2000 747.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_315 core 178.2000 745.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_314 core 178.2000 743.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_313 core 178.2000 741.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_312 core 178.2000 739.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_311 core 178.2000 738.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_310 core 178.2000 736.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_309 core 178.2000 734.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_308 core 178.2000 732.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_307 core 178.2000 730.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_306 core 178.2000 729.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_305 core 178.2000 727.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_304 core 178.2000 725.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_303 core 178.2000 723.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_302 core 178.2000 721.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_301 core 178.2000 720.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_300 core 178.2000 718.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_299 core 178.2000 716.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_298 core 178.2000 714.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_297 core 178.2000 712.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_296 core 178.2000 711.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_295 core 178.2000 709.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_294 core 178.2000 707.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_293 core 178.2000 705.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_292 core 178.2000 703.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_291 core 178.2000 702.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_290 core 178.2000 700.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_289 core 178.2000 698.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_288 core 178.2000 696.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_287 core 178.2000 694.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_286 core 178.2000 693.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_285 core 178.2000 691.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_284 core 178.2000 689.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_283 core 178.2000 687.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_282 core 178.2000 685.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_281 core 178.2000 684.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_280 core 178.2000 682.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_279 core 178.2000 680.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_278 core 178.2000 678.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_277 core 178.2000 676.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_276 core 178.2000 675.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_275 core 178.2000 673.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_274 core 178.2000 671.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_273 core 178.2000 669.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_272 core 178.2000 667.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_271 core 178.2000 666.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_270 core 178.2000 664.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_269 core 178.2000 662.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_268 core 178.2000 660.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_267 core 178.2000 658.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_266 core 178.2000 657.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_265 core 178.2000 655.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_264 core 178.2000 653.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_263 core 178.2000 651.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_262 core 178.2000 649.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_261 core 178.2000 648.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_260 core 178.2000 646.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_259 core 178.2000 644.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_258 core 178.2000 642.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_257 core 178.2000 640.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_256 core 178.2000 639.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_255 core 178.2000 637.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_254 core 178.2000 635.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_253 core 178.2000 633.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_252 core 178.2000 631.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_251 core 178.2000 630.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_250 core 178.2000 628.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_249 core 178.2000 626.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_248 core 178.2000 624.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_247 core 178.2000 622.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_246 core 178.2000 621.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_245 core 178.2000 619.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_244 core 178.2000 617.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_243 core 178.2000 615.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_242 core 178.2000 613.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_241 core 178.2000 612.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_240 core 178.2000 610.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_239 core 178.2000 608.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_238 core 178.2000 606.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_237 core 178.2000 604.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_236 core 178.2000 603.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_235 core 178.2000 601.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_234 core 178.2000 599.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_233 core 178.2000 597.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_232 core 178.2000 595.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_231 core 178.2000 594.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_230 core 178.2000 592.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_229 core 178.2000 590.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_228 core 178.2000 588.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_227 core 178.2000 586.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_226 core 178.2000 585.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_225 core 178.2000 583.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_224 core 178.2000 581.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_223 core 178.2000 579.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_222 core 178.2000 577.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_221 core 178.2000 576.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_220 core 178.2000 574.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_219 core 178.2000 572.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_218 core 178.2000 570.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_217 core 178.2000 568.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_216 core 178.2000 567.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_215 core 178.2000 565.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_214 core 178.2000 563.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_213 core 178.2000 561.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_212 core 178.2000 559.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_211 core 178.2000 558.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_210 core 178.2000 556.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_209 core 178.2000 554.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_208 core 178.2000 552.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_207 core 178.2000 550.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_206 core 178.2000 549.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_205 core 178.2000 547.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_204 core 178.2000 545.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_203 core 178.2000 543.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_202 core 178.2000 541.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_201 core 178.2000 540.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_200 core 178.2000 538.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_199 core 178.2000 536.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_198 core 178.2000 534.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_197 core 178.2000 532.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_196 core 178.2000 531.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_195 core 178.2000 529.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_194 core 178.2000 527.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_193 core 178.2000 525.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_192 core 178.2000 523.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_191 core 178.2000 522.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_190 core 178.2000 520.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_189 core 178.2000 518.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_188 core 178.2000 516.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_187 core 178.2000 514.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_186 core 178.2000 513.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_185 core 178.2000 511.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_184 core 178.2000 509.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_183 core 178.2000 507.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_182 core 178.2000 505.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_181 core 178.2000 504.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_180 core 178.2000 502.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_179 core 178.2000 500.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_178 core 178.2000 498.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_177 core 178.2000 496.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_176 core 178.2000 495.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_175 core 178.2000 493.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_174 core 178.2000 491.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_173 core 178.2000 489.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_172 core 178.2000 487.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_171 core 178.2000 486.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_170 core 178.2000 484.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_169 core 178.2000 482.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_168 core 178.2000 480.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_167 core 178.2000 478.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_166 core 178.2000 477.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_165 core 178.2000 475.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_164 core 178.2000 473.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_163 core 178.2000 471.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_162 core 178.2000 469.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_161 core 178.2000 468.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_160 core 178.2000 466.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_159 core 178.2000 464.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_158 core 178.2000 462.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_157 core 178.2000 460.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_156 core 178.2000 459.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_155 core 178.2000 457.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_154 core 178.2000 455.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_153 core 178.2000 453.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_152 core 178.2000 451.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_151 core 178.2000 450.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_150 core 178.2000 448.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_149 core 178.2000 446.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_148 core 178.2000 444.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_147 core 178.2000 442.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_146 core 178.2000 441.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_145 core 178.2000 439.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_144 core 178.2000 437.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_143 core 178.2000 435.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_142 core 178.2000 433.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_141 core 178.2000 432.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_140 core 178.2000 430.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_139 core 178.2000 428.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_138 core 178.2000 426.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_137 core 178.2000 424.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_136 core 178.2000 423.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_135 core 178.2000 421.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_134 core 178.2000 419.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_133 core 178.2000 417.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_132 core 178.2000 415.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_131 core 178.2000 414.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_130 core 178.2000 412.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_129 core 178.2000 410.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_128 core 178.2000 408.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_127 core 178.2000 406.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_126 core 178.2000 405.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_125 core 178.2000 403.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_124 core 178.2000 401.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_123 core 178.2000 399.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_122 core 178.2000 397.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_121 core 178.2000 396.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_120 core 178.2000 394.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_119 core 178.2000 392.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_118 core 178.2000 390.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_117 core 178.2000 388.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_116 core 178.2000 387.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_115 core 178.2000 385.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_114 core 178.2000 383.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_113 core 178.2000 381.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_112 core 178.2000 379.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_111 core 178.2000 378.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_110 core 178.2000 376.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_109 core 178.2000 374.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_108 core 178.2000 372.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_107 core 178.2000 370.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_106 core 178.2000 369.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_105 core 178.2000 367.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_104 core 178.2000 365.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_103 core 178.2000 363.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_102 core 178.2000 361.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_101 core 178.2000 360.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_100 core 178.2000 358.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_99 core 178.2000 356.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_98 core 178.2000 354.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_97 core 178.2000 352.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_96 core 178.2000 351.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_95 core 178.2000 349.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_94 core 178.2000 347.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_93 core 178.2000 345.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_92 core 178.2000 343.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_91 core 178.2000 342.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_90 core 178.2000 340.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_89 core 178.2000 338.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_88 core 178.2000 336.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_87 core 178.2000 334.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_86 core 178.2000 333.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_85 core 178.2000 331.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_84 core 178.2000 329.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_83 core 178.2000 327.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_82 core 178.2000 325.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_81 core 178.2000 324.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_80 core 178.2000 322.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_79 core 178.2000 320.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_78 core 178.2000 318.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_77 core 178.2000 316.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_76 core 178.2000 315.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_75 core 178.2000 313.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_74 core 178.2000 311.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_73 core 178.2000 309.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_72 core 178.2000 307.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_71 core 178.2000 306.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_70 core 178.2000 304.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_69 core 178.2000 302.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_68 core 178.2000 300.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_67 core 178.2000 298.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_66 core 178.2000 297.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_65 core 178.2000 295.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_64 core 178.2000 293.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_63 core 178.2000 291.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_62 core 178.2000 289.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_61 core 178.2000 288.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_60 core 178.2000 286.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_59 core 178.2000 284.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_58 core 178.2000 282.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_57 core 178.2000 280.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_56 core 178.2000 279.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_55 core 178.2000 277.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_54 core 178.2000 275.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_53 core 178.2000 273.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_52 core 178.2000 271.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_51 core 178.2000 270.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_50 core 178.2000 268.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_49 core 178.2000 266.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_48 core 178.2000 264.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_47 core 178.2000 262.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_46 core 178.2000 261.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_45 core 178.2000 259.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_44 core 178.2000 257.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_43 core 178.2000 255.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_42 core 178.2000 253.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_41 core 178.2000 252.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_40 core 178.2000 250.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_39 core 178.2000 248.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_38 core 178.2000 246.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_37 core 178.2000 244.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_36 core 178.2000 243.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_35 core 178.2000 241.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_34 core 178.2000 239.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_33 core 178.2000 237.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_32 core 178.2000 235.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_31 core 178.2000 234.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_30 core 178.2000 232.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_29 core 178.2000 230.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_28 core 178.2000 228.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_27 core 178.2000 226.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_26 core 178.2000 225.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_25 core 178.2000 223.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_24 core 178.2000 221.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_23 core 178.2000 219.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_22 core 178.2000 217.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_21 core 178.2000 216.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_20 core 178.2000 214.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_19 core 178.2000 212.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_18 core 178.2000 210.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_17 core 178.2000 208.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_16 core 178.2000 207.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_15 core 178.2000 205.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_14 core 178.2000 203.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_13 core 178.2000 201.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_12 core 178.2000 199.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_11 core 178.2000 198.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_10 core 178.2000 196.2000 FS 3218 1 0.2000 0.0000
DefRow: ROW_9 core 178.2000 194.4000 N 3218 1 0.2000 0.0000
DefRow: ROW_8 core 178.2000 192.6000 FS 3218 1 0.2000 0.0000
DefRow: ROW_7 core 178.2000 190.8000 N 3218 1 0.2000 0.0000
DefRow: ROW_6 core 178.2000 189.0000 FS 3218 1 0.2000 0.0000
DefRow: ROW_5 core 178.2000 187.2000 N 3218 1 0.2000 0.0000
DefRow: ROW_4 core 178.2000 185.4000 FS 3218 1 0.2000 0.0000
DefRow: ROW_3 core 178.2000 183.6000 N 3218 1 0.2000 0.0000
DefRow: ROW_2 core 178.2000 181.8000 FS 3218 1 0.2000 0.0000
DefRow: ROW_1 core 178.2000 180.0000 N 3218 1 0.2000 0.0000
DefRow: ROW_0 core 178.2000 178.2000 FS 3218 1 0.2000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 2.2000 250 4.0000 1 10
Track: X 9.3000 153 6.5000 1 10
Track: X 0.7000 1250 0.8000 1 9
Track: Y 2.2000 250 4.0000 1 9
Track: Y 0.2000 4999 0.2000 1 8
Track: X 0.7000 1250 0.8000 1 8
Track: X 0.1000 5000 0.2000 1 7
Track: Y 0.2000 4999 0.2000 1 7
Track: Y 0.2000 4999 0.2000 1 6
Track: X 0.1000 5000 0.2000 1 6
Track: X 0.1000 5000 0.2000 1 5
Track: Y 0.2000 4999 0.2000 1 5
Track: Y 0.2000 4999 0.2000 1 4
Track: X 0.1000 5000 0.2000 1 4
Track: X 0.1000 5000 0.2000 1 3
Track: Y 0.2000 4999 0.2000 1 3
Track: Y 0.2000 4999 0.2000 1 2
Track: X 0.1000 5000 0.2000 1 2
Track: X 0.1000 5000 0.2000 1 1
Track: Y 0.2000 4999 0.2000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: Y 0.0000 2 0.2000
GCellGrid: Y 0.2000 500 2.0000
GCellGrid: Y 998.2000 2 1.8000
GCellGrid: X 0.0000 2 0.1000
GCellGrid: X 0.1000 500 2.0000
GCellGrid: X 998.1000 2 1.9000

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <macro_place_constraint>                                               #
#          ...                                                            #
#  </macro_place_constraint>                                              #
###########################################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################
Block: arm_boot_inst MX 178.2000 178.2000 01
Block: mem_inst/m1 R0 235.2100 449.6350 01
Block: mem_inst/m2 R180 504.0100 178.2000 01
Block: p1 R90 889.9850 187.7100 01
Block: p2 R90 889.9850 242.2200 01
Block: p3 R90 889.9850 296.7300 01
Block: p4 R90 889.9850 351.2400 01
Block: p5 R90 889.9850 405.7450 01
Block: p6 R90 889.9850 460.2500 01
Block: p7 R90 889.9850 514.7550 01
Block: p8 R90 889.9850 569.2600 01
Block: p9 R90 889.9850 623.7650 01
Block: p10 R90 889.9850 678.2700 01
Block: p11 R90 889.9850 732.7800 01
Block: p12 R90 889.9850 787.2900 01
Block: p13 R180 787.2900 889.9850 01
Block: p14 R180 732.7800 889.9850 01
Block: p15 R180 678.2700 889.9850 01
Block: p16 R180 623.7650 889.9850 01
Block: p17 R180 569.2600 889.9850 01
Block: p18 R180 514.7550 889.9850 01
Block: p19 R180 460.2500 889.9850 01
Block: p20 R180 405.7450 889.9850 01
Block: p21 R180 351.2400 889.9850 01
Block: p22 R180 296.7300 889.9850 01
Block: p23 R180 242.2200 889.9850 01
Block: p24 R180 187.7100 889.9850 01
Block: p25 R270 20.0150 787.2900 01
Block: p26 R270 20.0150 732.7800 01
Block: p27 R270 20.0150 678.2700 01
Block: p28 R270 20.0150 623.7650 01
Block: p29 R270 20.0150 569.2600 01
Block: p30 R270 20.0150 514.7550 01
Block: p31 R270 20.0150 460.2500 01
Block: p32 R270 20.0150 405.7450 01
Block: p33 R270 20.0150 351.2400 01
Block: p34 R270 20.0150 296.7300 01
Block: p35 R270 20.0150 242.2200 01
Block: p36 R270 20.0150 187.7100 01
Block: p37 R0 187.7100 20.0150 01
Block: p38 R0 242.2200 20.0150 01
Block: p39 R0 296.7300 20.0150 01
Block: p40 R0 351.2400 20.0150 01
Block: p41 R0 405.7450 20.0150 01
Block: p42 R0 460.2500 20.0150 01
Block: p43 R0 514.7550 20.0150 01
Block: p44 R0 569.2600 20.0150 01
Block: p45 R0 623.7650 20.0150 01
Block: p46 R0 678.2700 20.0150 01
Block: p47 R0 732.7800 20.0150 01
Block: p48 R0 787.2900 20.0150 01

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinSpacing layer=layerId spacing=val />                        #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d spacing=val />   #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="top" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3ff orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################################
#  <RouteBlockages>                                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes coreeolblkg=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                                      #
#     </Blockage>                                                                                                        #
#  </RouteBlockages>                                                                                                     #
##########################################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################


#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: FILLER_N_111 PFILLER20_G 158.2000 841.8000 N R180 - 00
IO: FILLER_N_112 PFILLER20_G 212.7100 841.8000 N R180 - 00
IO: FILLER_N_113 PFILLER20_G 267.2200 841.8000 N R180 - 00
IO: FILLER_N_114 PFILLER20_G 321.7300 841.8000 N R180 - 00
IO: FILLER_N_115 PFILLER20_G 376.2400 841.8000 N R180 - 00
IO: FILLER_N_116 PFILLER20_G 430.7450 841.8000 N R180 - 00
IO: FILLER_N_117 PFILLER20_G 485.2500 841.8000 N R180 - 00
IO: FILLER_N_118 PFILLER20_G 539.7550 841.8000 N R180 - 00
IO: FILLER_N_119 PFILLER20_G 594.2600 841.8000 N R180 - 00
IO: FILLER_N_120 PFILLER20_G 648.7650 841.8000 N R180 - 00
IO: FILLER_N_121 PFILLER20_G 703.2700 841.8000 N R180 - 00
IO: FILLER_N_122 PFILLER20_G 757.7800 841.8000 N R180 - 00
IO: FILLER_N_123 PFILLER20_G 812.2900 841.8000 N R180 - 00
IO: FILLER_N_124 PFILLER5_G 178.2000 841.8000 N R180 - 00
IO: FILLER_N_125 PFILLER5_G 232.7100 841.8000 N R180 - 00
IO: FILLER_N_126 PFILLER5_G 287.2200 841.8000 N R180 - 00
IO: FILLER_N_127 PFILLER5_G 341.7300 841.8000 N R180 - 00
IO: FILLER_N_128 PFILLER5_G 396.2400 841.8000 N R180 - 00
IO: FILLER_N_129 PFILLER5_G 450.7450 841.8000 N R180 - 00
IO: FILLER_N_130 PFILLER5_G 505.2500 841.8000 N R180 - 00
IO: FILLER_N_131 PFILLER5_G 559.7550 841.8000 N R180 - 00
IO: FILLER_N_132 PFILLER5_G 614.2600 841.8000 N R180 - 00
IO: FILLER_N_133 PFILLER5_G 668.7650 841.8000 N R180 - 00
IO: FILLER_N_134 PFILLER5_G 723.2700 841.8000 N R180 - 00
IO: FILLER_N_135 PFILLER5_G 777.7800 841.8000 N R180 - 00
IO: FILLER_N_136 PFILLER5_G 832.2900 841.8000 N R180 - 00
IO: FILLER_N_137 PFILLER1_G 183.2000 841.8000 N R180 - 00
IO: FILLER_N_138 PFILLER1_G 184.2000 841.8000 N R180 - 00
IO: FILLER_N_139 PFILLER1_G 185.2000 841.8000 N R180 - 00
IO: FILLER_N_140 PFILLER1_G 186.2000 841.8000 N R180 - 00
IO: FILLER_N_141 PFILLER1_G 237.7100 841.8000 N R180 - 00
IO: FILLER_N_142 PFILLER1_G 238.7100 841.8000 N R180 - 00
IO: FILLER_N_143 PFILLER1_G 239.7100 841.8000 N R180 - 00
IO: FILLER_N_144 PFILLER1_G 240.7100 841.8000 N R180 - 00
IO: FILLER_N_145 PFILLER1_G 292.2200 841.8000 N R180 - 00
IO: FILLER_N_146 PFILLER1_G 293.2200 841.8000 N R180 - 00
IO: FILLER_N_147 PFILLER1_G 294.2200 841.8000 N R180 - 00
IO: FILLER_N_148 PFILLER1_G 295.2200 841.8000 N R180 - 00
IO: FILLER_N_149 PFILLER1_G 346.7300 841.8000 N R180 - 00
IO: FILLER_N_150 PFILLER1_G 347.7300 841.8000 N R180 - 00
IO: FILLER_N_151 PFILLER1_G 348.7300 841.8000 N R180 - 00
IO: FILLER_N_152 PFILLER1_G 349.7300 841.8000 N R180 - 00
IO: FILLER_N_153 PFILLER1_G 401.2400 841.8000 N R180 - 00
IO: FILLER_N_154 PFILLER1_G 402.2400 841.8000 N R180 - 00
IO: FILLER_N_155 PFILLER1_G 403.2400 841.8000 N R180 - 00
IO: FILLER_N_156 PFILLER1_G 404.2400 841.8000 N R180 - 00
IO: FILLER_N_157 PFILLER1_G 455.7450 841.8000 N R180 - 00
IO: FILLER_N_158 PFILLER1_G 456.7450 841.8000 N R180 - 00
IO: FILLER_N_159 PFILLER1_G 457.7450 841.8000 N R180 - 00
IO: FILLER_N_160 PFILLER1_G 458.7450 841.8000 N R180 - 00
IO: FILLER_N_161 PFILLER1_G 510.2500 841.8000 N R180 - 00
IO: FILLER_N_162 PFILLER1_G 511.2500 841.8000 N R180 - 00
IO: FILLER_N_163 PFILLER1_G 512.2500 841.8000 N R180 - 00
IO: FILLER_N_164 PFILLER1_G 513.2500 841.8000 N R180 - 00
IO: FILLER_N_165 PFILLER1_G 564.7550 841.8000 N R180 - 00
IO: FILLER_N_166 PFILLER1_G 565.7550 841.8000 N R180 - 00
IO: FILLER_N_167 PFILLER1_G 566.7550 841.8000 N R180 - 00
IO: FILLER_N_168 PFILLER1_G 567.7550 841.8000 N R180 - 00
IO: FILLER_N_169 PFILLER1_G 619.2600 841.8000 N R180 - 00
IO: FILLER_N_170 PFILLER1_G 620.2600 841.8000 N R180 - 00
IO: FILLER_N_171 PFILLER1_G 621.2600 841.8000 N R180 - 00
IO: FILLER_N_172 PFILLER1_G 622.2600 841.8000 N R180 - 00
IO: FILLER_N_173 PFILLER1_G 673.7650 841.8000 N R180 - 00
IO: FILLER_N_174 PFILLER1_G 674.7650 841.8000 N R180 - 00
IO: FILLER_N_175 PFILLER1_G 675.7650 841.8000 N R180 - 00
IO: FILLER_N_176 PFILLER1_G 676.7650 841.8000 N R180 - 00
IO: FILLER_N_177 PFILLER1_G 728.2700 841.8000 N R180 - 00
IO: FILLER_N_178 PFILLER1_G 729.2700 841.8000 N R180 - 00
IO: FILLER_N_179 PFILLER1_G 730.2700 841.8000 N R180 - 00
IO: FILLER_N_180 PFILLER1_G 731.2700 841.8000 N R180 - 00
IO: FILLER_N_181 PFILLER1_G 782.7800 841.8000 N R180 - 00
IO: FILLER_N_182 PFILLER1_G 783.7800 841.8000 N R180 - 00
IO: FILLER_N_183 PFILLER1_G 784.7800 841.8000 N R180 - 00
IO: FILLER_N_184 PFILLER1_G 785.7800 841.8000 N R180 - 00
IO: FILLER_N_185 PFILLER1_G 837.2900 841.8000 N R180 - 00
IO: FILLER_N_186 PFILLER1_G 838.2900 841.8000 N R180 - 00
IO: FILLER_N_187 PFILLER1_G 839.2900 841.8000 N R180 - 00
IO: FILLER_N_188 PFILLER1_G 840.2900 841.8000 N R180 - 00
IO: FILLER_N_189 PFILLER05_G 187.2000 841.8000 N R180 - 00
IO: FILLER_N_190 PFILLER05_G 241.7100 841.8000 N R180 - 00
IO: FILLER_N_191 PFILLER05_G 296.2200 841.8000 N R180 - 00
IO: FILLER_N_192 PFILLER05_G 350.7300 841.8000 N R180 - 00
IO: FILLER_N_193 PFILLER05_G 405.2400 841.8000 N R180 - 00
IO: FILLER_N_194 PFILLER05_G 459.7450 841.8000 N R180 - 00
IO: FILLER_N_195 PFILLER05_G 514.2500 841.8000 N R180 - 00
IO: FILLER_N_196 PFILLER05_G 568.7550 841.8000 N R180 - 00
IO: FILLER_N_197 PFILLER05_G 623.2600 841.8000 N R180 - 00
IO: FILLER_N_198 PFILLER05_G 677.7650 841.8000 N R180 - 00
IO: FILLER_N_199 PFILLER05_G 732.2700 841.8000 N R180 - 00
IO: FILLER_N_200 PFILLER05_G 786.7800 841.8000 N R180 - 00
IO: FILLER_N_201 PFILLER05_G 841.2900 841.8000 N R180 - 00
IO: FILLER_N_202 PFILLER0005_G 187.7000 841.8000 N R180 - 00
IO: FILLER_N_203 PFILLER0005_G 187.7050 841.8000 N R180 - 00
IO: FILLER_N_204 PFILLER0005_G 242.2100 841.8000 N R180 - 00
IO: FILLER_N_205 PFILLER0005_G 242.2150 841.8000 N R180 - 00
IO: FILLER_N_206 PFILLER0005_G 296.7200 841.8000 N R180 - 00
IO: FILLER_N_207 PFILLER0005_G 296.7250 841.8000 N R180 - 00
IO: FILLER_N_208 PFILLER0005_G 351.2300 841.8000 N R180 - 00
IO: FILLER_N_209 PFILLER0005_G 351.2350 841.8000 N R180 - 00
IO: FILLER_N_210 PFILLER0005_G 405.7400 841.8000 N R180 - 00
IO: FILLER_N_211 PFILLER0005_G 460.2450 841.8000 N R180 - 00
IO: FILLER_N_212 PFILLER0005_G 514.7500 841.8000 N R180 - 00
IO: FILLER_N_213 PFILLER0005_G 569.2550 841.8000 N R180 - 00
IO: FILLER_N_214 PFILLER0005_G 623.7600 841.8000 N R180 - 00
IO: FILLER_N_215 PFILLER0005_G 678.2650 841.8000 N R180 - 00
IO: FILLER_N_216 PFILLER0005_G 732.7700 841.8000 N R180 - 00
IO: FILLER_N_217 PFILLER0005_G 732.7750 841.8000 N R180 - 00
IO: FILLER_N_218 PFILLER0005_G 787.2800 841.8000 N R180 - 00
IO: FILLER_N_219 PFILLER0005_G 787.2850 841.8000 N R180 - 00
IO: FILLER_N_220 PFILLER0005_G 841.7900 841.8000 N R180 - 00
IO: FILLER_N_221 PFILLER0005_G 841.7950 841.8000 N R180 - 00
IO: vss_inst0 PVSS1DGZ_G 187.7100 841.8000 N R180 - 01
IO: vdd_inst0 PVDD1DGZ_G 242.2200 841.8000 N R180 - 01
IO: gpio_0 PDUW04DGZ_G 678.2700 841.8000 N R180 - 01
IO: spi_ss PDUW04DGZ_G 623.7650 841.8000 N R180 - 01
IO: spi_sck PDUW04DGZ_G 569.2600 841.8000 N R180 - 01
IO: spi_mosi PDUW04DGZ_G 514.7550 841.8000 N R180 - 01
IO: spi_miso PDUW04DGZ_G 460.2500 841.8000 N R180 - 01
IO: vdd2poc_inst PVDD2POC_G 405.7450 841.8000 N R180 - 01
IO: uart_rx PDUW04DGZ_G 351.2400 841.8000 N R180 - 01
IO: uart_tx PDUW04DGZ_G 296.7300 841.8000 N R180 - 01
IO: vddpst_inst0 PVDD2DGZ_G 732.7800 841.8000 N R180 - 01
IO: vsspst_inst0 PVSS2DGZ_G 787.2900 841.8000 N R180 - 01
IO: p_tr PCORNER_G 841.8000 841.8000 NE R180 - 00
IO: FILLER_W_0 PFILLER20_G 23.2000 158.2000 W R270 - 00
IO: FILLER_W_1 PFILLER20_G 23.2000 212.7100 W R270 - 00
IO: FILLER_W_2 PFILLER20_G 23.2000 267.2200 W R270 - 00
IO: FILLER_W_3 PFILLER20_G 23.2000 321.7300 W R270 - 00
IO: FILLER_W_4 PFILLER20_G 23.2000 376.2400 W R270 - 00
IO: FILLER_W_5 PFILLER20_G 23.2000 430.7450 W R270 - 00
IO: FILLER_W_6 PFILLER20_G 23.2000 485.2500 W R270 - 00
IO: FILLER_W_7 PFILLER20_G 23.2000 539.7550 W R270 - 00
IO: FILLER_W_8 PFILLER20_G 23.2000 594.2600 W R270 - 00
IO: FILLER_W_9 PFILLER20_G 23.2000 648.7650 W R270 - 00
IO: FILLER_W_10 PFILLER20_G 23.2000 703.2700 W R270 - 00
IO: FILLER_W_11 PFILLER20_G 23.2000 757.7800 W R270 - 00
IO: FILLER_W_12 PFILLER20_G 23.2000 812.2900 W R270 - 00
IO: FILLER_W_13 PFILLER5_G 23.2000 178.2000 W R270 - 00
IO: FILLER_W_14 PFILLER5_G 23.2000 232.7100 W R270 - 00
IO: FILLER_W_15 PFILLER5_G 23.2000 287.2200 W R270 - 00
IO: FILLER_W_16 PFILLER5_G 23.2000 341.7300 W R270 - 00
IO: FILLER_W_17 PFILLER5_G 23.2000 396.2400 W R270 - 00
IO: FILLER_W_18 PFILLER5_G 23.2000 450.7450 W R270 - 00
IO: FILLER_W_19 PFILLER5_G 23.2000 505.2500 W R270 - 00
IO: FILLER_W_20 PFILLER5_G 23.2000 559.7550 W R270 - 00
IO: FILLER_W_21 PFILLER5_G 23.2000 614.2600 W R270 - 00
IO: FILLER_W_22 PFILLER5_G 23.2000 668.7650 W R270 - 00
IO: FILLER_W_23 PFILLER5_G 23.2000 723.2700 W R270 - 00
IO: FILLER_W_24 PFILLER5_G 23.2000 777.7800 W R270 - 00
IO: FILLER_W_25 PFILLER5_G 23.2000 832.2900 W R270 - 00
IO: FILLER_W_26 PFILLER1_G 23.2000 183.2000 W R270 - 00
IO: FILLER_W_27 PFILLER1_G 23.2000 184.2000 W R270 - 00
IO: FILLER_W_28 PFILLER1_G 23.2000 185.2000 W R270 - 00
IO: FILLER_W_29 PFILLER1_G 23.2000 186.2000 W R270 - 00
IO: FILLER_W_30 PFILLER1_G 23.2000 237.7100 W R270 - 00
IO: FILLER_W_31 PFILLER1_G 23.2000 238.7100 W R270 - 00
IO: FILLER_W_32 PFILLER1_G 23.2000 239.7100 W R270 - 00
IO: FILLER_W_33 PFILLER1_G 23.2000 240.7100 W R270 - 00
IO: FILLER_W_34 PFILLER1_G 23.2000 292.2200 W R270 - 00
IO: FILLER_W_35 PFILLER1_G 23.2000 293.2200 W R270 - 00
IO: FILLER_W_36 PFILLER1_G 23.2000 294.2200 W R270 - 00
IO: FILLER_W_37 PFILLER1_G 23.2000 295.2200 W R270 - 00
IO: FILLER_W_38 PFILLER1_G 23.2000 346.7300 W R270 - 00
IO: FILLER_W_39 PFILLER1_G 23.2000 347.7300 W R270 - 00
IO: FILLER_W_40 PFILLER1_G 23.2000 348.7300 W R270 - 00
IO: FILLER_W_41 PFILLER1_G 23.2000 349.7300 W R270 - 00
IO: FILLER_W_42 PFILLER1_G 23.2000 401.2400 W R270 - 00
IO: FILLER_W_43 PFILLER1_G 23.2000 402.2400 W R270 - 00
IO: FILLER_W_44 PFILLER1_G 23.2000 403.2400 W R270 - 00
IO: FILLER_W_45 PFILLER1_G 23.2000 404.2400 W R270 - 00
IO: FILLER_W_46 PFILLER1_G 23.2000 455.7450 W R270 - 00
IO: FILLER_W_47 PFILLER1_G 23.2000 456.7450 W R270 - 00
IO: FILLER_W_48 PFILLER1_G 23.2000 457.7450 W R270 - 00
IO: FILLER_W_49 PFILLER1_G 23.2000 458.7450 W R270 - 00
IO: FILLER_W_50 PFILLER1_G 23.2000 510.2500 W R270 - 00
IO: FILLER_W_51 PFILLER1_G 23.2000 511.2500 W R270 - 00
IO: FILLER_W_52 PFILLER1_G 23.2000 512.2500 W R270 - 00
IO: FILLER_W_53 PFILLER1_G 23.2000 513.2500 W R270 - 00
IO: FILLER_W_54 PFILLER1_G 23.2000 564.7550 W R270 - 00
IO: FILLER_W_55 PFILLER1_G 23.2000 565.7550 W R270 - 00
IO: FILLER_W_56 PFILLER1_G 23.2000 566.7550 W R270 - 00
IO: FILLER_W_57 PFILLER1_G 23.2000 567.7550 W R270 - 00
IO: FILLER_W_58 PFILLER1_G 23.2000 619.2600 W R270 - 00
IO: FILLER_W_59 PFILLER1_G 23.2000 620.2600 W R270 - 00
IO: FILLER_W_60 PFILLER1_G 23.2000 621.2600 W R270 - 00
IO: FILLER_W_61 PFILLER1_G 23.2000 622.2600 W R270 - 00
IO: FILLER_W_62 PFILLER1_G 23.2000 673.7650 W R270 - 00
IO: FILLER_W_63 PFILLER1_G 23.2000 674.7650 W R270 - 00
IO: FILLER_W_64 PFILLER1_G 23.2000 675.7650 W R270 - 00
IO: FILLER_W_65 PFILLER1_G 23.2000 676.7650 W R270 - 00
IO: FILLER_W_66 PFILLER1_G 23.2000 728.2700 W R270 - 00
IO: FILLER_W_67 PFILLER1_G 23.2000 729.2700 W R270 - 00
IO: FILLER_W_68 PFILLER1_G 23.2000 730.2700 W R270 - 00
IO: FILLER_W_69 PFILLER1_G 23.2000 731.2700 W R270 - 00
IO: FILLER_W_70 PFILLER1_G 23.2000 782.7800 W R270 - 00
IO: FILLER_W_71 PFILLER1_G 23.2000 783.7800 W R270 - 00
IO: FILLER_W_72 PFILLER1_G 23.2000 784.7800 W R270 - 00
IO: FILLER_W_73 PFILLER1_G 23.2000 785.7800 W R270 - 00
IO: FILLER_W_74 PFILLER1_G 23.2000 837.2900 W R270 - 00
IO: FILLER_W_75 PFILLER1_G 23.2000 838.2900 W R270 - 00
IO: FILLER_W_76 PFILLER1_G 23.2000 839.2900 W R270 - 00
IO: FILLER_W_77 PFILLER1_G 23.2000 840.2900 W R270 - 00
IO: FILLER_W_78 PFILLER05_G 23.2000 187.2000 W R270 - 00
IO: FILLER_W_79 PFILLER05_G 23.2000 241.7100 W R270 - 00
IO: FILLER_W_80 PFILLER05_G 23.2000 296.2200 W R270 - 00
IO: FILLER_W_81 PFILLER05_G 23.2000 350.7300 W R270 - 00
IO: FILLER_W_82 PFILLER05_G 23.2000 405.2400 W R270 - 00
IO: FILLER_W_83 PFILLER05_G 23.2000 459.7450 W R270 - 00
IO: FILLER_W_84 PFILLER05_G 23.2000 514.2500 W R270 - 00
IO: FILLER_W_85 PFILLER05_G 23.2000 568.7550 W R270 - 00
IO: FILLER_W_86 PFILLER05_G 23.2000 623.2600 W R270 - 00
IO: FILLER_W_87 PFILLER05_G 23.2000 677.7650 W R270 - 00
IO: FILLER_W_88 PFILLER05_G 23.2000 732.2700 W R270 - 00
IO: FILLER_W_89 PFILLER05_G 23.2000 786.7800 W R270 - 00
IO: FILLER_W_90 PFILLER05_G 23.2000 841.2900 W R270 - 00
IO: FILLER_W_91 PFILLER0005_G 23.2000 187.7000 W R270 - 00
IO: FILLER_W_92 PFILLER0005_G 23.2000 187.7050 W R270 - 00
IO: FILLER_W_93 PFILLER0005_G 23.2000 242.2100 W R270 - 00
IO: FILLER_W_94 PFILLER0005_G 23.2000 242.2150 W R270 - 00
IO: FILLER_W_95 PFILLER0005_G 23.2000 296.7200 W R270 - 00
IO: FILLER_W_96 PFILLER0005_G 23.2000 296.7250 W R270 - 00
IO: FILLER_W_97 PFILLER0005_G 23.2000 351.2300 W R270 - 00
IO: FILLER_W_98 PFILLER0005_G 23.2000 351.2350 W R270 - 00
IO: FILLER_W_99 PFILLER0005_G 23.2000 405.7400 W R270 - 00
IO: FILLER_W_100 PFILLER0005_G 23.2000 460.2450 W R270 - 00
IO: FILLER_W_101 PFILLER0005_G 23.2000 514.7500 W R270 - 00
IO: FILLER_W_102 PFILLER0005_G 23.2000 569.2550 W R270 - 00
IO: FILLER_W_103 PFILLER0005_G 23.2000 623.7600 W R270 - 00
IO: FILLER_W_104 PFILLER0005_G 23.2000 678.2650 W R270 - 00
IO: FILLER_W_105 PFILLER0005_G 23.2000 732.7700 W R270 - 00
IO: FILLER_W_106 PFILLER0005_G 23.2000 732.7750 W R270 - 00
IO: FILLER_W_107 PFILLER0005_G 23.2000 787.2800 W R270 - 00
IO: FILLER_W_108 PFILLER0005_G 23.2000 787.2850 W R270 - 00
IO: FILLER_W_109 PFILLER0005_G 23.2000 841.7900 W R270 - 00
IO: FILLER_W_110 PFILLER0005_G 23.2000 841.7950 W R270 - 00
IO: vsspst_inst4 PVSS2DGZ_G 23.2000 787.2900 W R270 - 01
IO: gpio_2 PDUW04DGZ_G 23.2000 732.7800 W R270 - 01
IO: gpio_14 PDUW04DGZ_G 23.2000 678.2700 W R270 - 01
IO: gpio_13 PDUW04DGZ_G 23.2000 623.7650 W R270 - 01
IO: gpio_12 PDUW04DGZ_G 23.2000 569.2600 W R270 - 01
IO: tck_cell PDUW04DGZ_G 23.2000 514.7550 W R270 - 01
IO: clk_cell PDUW04DGZ_G 23.2000 460.2500 W R270 - 01
IO: gpio_11 PDUW04DGZ_G 23.2000 405.7450 W R270 - 01
IO: reset_cell PDDW04DGZ_G 23.2000 351.2400 W R270 - 01
IO: gpio_1 PDUW04DGZ_G 23.2000 296.7300 W R270 - 01
IO: vddpst_inst1 PVDD2DGZ_G 23.2000 242.2200 W R270 - 01
IO: vsspst_inst1 PVSS2DGZ_G 23.2000 187.7100 W R270 - 01
IO: p_tl PCORNER_G 23.2000 841.8000 NW R270 - 00
IO: FILLER_S_111 PFILLER20_G 158.2000 23.2000 S R0 - 00
IO: FILLER_S_112 PFILLER20_G 212.7100 23.2000 S R0 - 00
IO: FILLER_S_113 PFILLER20_G 267.2200 23.2000 S R0 - 00
IO: FILLER_S_114 PFILLER20_G 321.7300 23.2000 S R0 - 00
IO: FILLER_S_115 PFILLER20_G 376.2400 23.2000 S R0 - 00
IO: FILLER_S_116 PFILLER20_G 430.7450 23.2000 S R0 - 00
IO: FILLER_S_117 PFILLER20_G 485.2500 23.2000 S R0 - 00
IO: FILLER_S_118 PFILLER20_G 539.7550 23.2000 S R0 - 00
IO: FILLER_S_119 PFILLER20_G 594.2600 23.2000 S R0 - 00
IO: FILLER_S_120 PFILLER20_G 648.7650 23.2000 S R0 - 00
IO: FILLER_S_121 PFILLER20_G 703.2700 23.2000 S R0 - 00
IO: FILLER_S_122 PFILLER20_G 757.7800 23.2000 S R0 - 00
IO: FILLER_S_123 PFILLER20_G 812.2900 23.2000 S R0 - 00
IO: FILLER_S_124 PFILLER5_G 178.2000 23.2000 S R0 - 00
IO: FILLER_S_125 PFILLER5_G 232.7100 23.2000 S R0 - 00
IO: FILLER_S_126 PFILLER5_G 287.2200 23.2000 S R0 - 00
IO: FILLER_S_127 PFILLER5_G 341.7300 23.2000 S R0 - 00
IO: FILLER_S_128 PFILLER5_G 396.2400 23.2000 S R0 - 00
IO: FILLER_S_129 PFILLER5_G 450.7450 23.2000 S R0 - 00
IO: FILLER_S_130 PFILLER5_G 505.2500 23.2000 S R0 - 00
IO: FILLER_S_131 PFILLER5_G 559.7550 23.2000 S R0 - 00
IO: FILLER_S_132 PFILLER5_G 614.2600 23.2000 S R0 - 00
IO: FILLER_S_133 PFILLER5_G 668.7650 23.2000 S R0 - 00
IO: FILLER_S_134 PFILLER5_G 723.2700 23.2000 S R0 - 00
IO: FILLER_S_135 PFILLER5_G 777.7800 23.2000 S R0 - 00
IO: FILLER_S_136 PFILLER5_G 832.2900 23.2000 S R0 - 00
IO: FILLER_S_137 PFILLER1_G 183.2000 23.2000 S R0 - 00
IO: FILLER_S_138 PFILLER1_G 184.2000 23.2000 S R0 - 00
IO: FILLER_S_139 PFILLER1_G 185.2000 23.2000 S R0 - 00
IO: FILLER_S_140 PFILLER1_G 186.2000 23.2000 S R0 - 00
IO: FILLER_S_141 PFILLER1_G 237.7100 23.2000 S R0 - 00
IO: FILLER_S_142 PFILLER1_G 238.7100 23.2000 S R0 - 00
IO: FILLER_S_143 PFILLER1_G 239.7100 23.2000 S R0 - 00
IO: FILLER_S_144 PFILLER1_G 240.7100 23.2000 S R0 - 00
IO: FILLER_S_145 PFILLER1_G 292.2200 23.2000 S R0 - 00
IO: FILLER_S_146 PFILLER1_G 293.2200 23.2000 S R0 - 00
IO: FILLER_S_147 PFILLER1_G 294.2200 23.2000 S R0 - 00
IO: FILLER_S_148 PFILLER1_G 295.2200 23.2000 S R0 - 00
IO: FILLER_S_149 PFILLER1_G 346.7300 23.2000 S R0 - 00
IO: FILLER_S_150 PFILLER1_G 347.7300 23.2000 S R0 - 00
IO: FILLER_S_151 PFILLER1_G 348.7300 23.2000 S R0 - 00
IO: FILLER_S_152 PFILLER1_G 349.7300 23.2000 S R0 - 00
IO: FILLER_S_153 PFILLER1_G 401.2400 23.2000 S R0 - 00
IO: FILLER_S_154 PFILLER1_G 402.2400 23.2000 S R0 - 00
IO: FILLER_S_155 PFILLER1_G 403.2400 23.2000 S R0 - 00
IO: FILLER_S_156 PFILLER1_G 404.2400 23.2000 S R0 - 00
IO: FILLER_S_157 PFILLER1_G 455.7450 23.2000 S R0 - 00
IO: FILLER_S_158 PFILLER1_G 456.7450 23.2000 S R0 - 00
IO: FILLER_S_159 PFILLER1_G 457.7450 23.2000 S R0 - 00
IO: FILLER_S_160 PFILLER1_G 458.7450 23.2000 S R0 - 00
IO: FILLER_S_161 PFILLER1_G 510.2500 23.2000 S R0 - 00
IO: FILLER_S_162 PFILLER1_G 511.2500 23.2000 S R0 - 00
IO: FILLER_S_163 PFILLER1_G 512.2500 23.2000 S R0 - 00
IO: FILLER_S_164 PFILLER1_G 513.2500 23.2000 S R0 - 00
IO: FILLER_S_165 PFILLER1_G 564.7550 23.2000 S R0 - 00
IO: FILLER_S_166 PFILLER1_G 565.7550 23.2000 S R0 - 00
IO: FILLER_S_167 PFILLER1_G 566.7550 23.2000 S R0 - 00
IO: FILLER_S_168 PFILLER1_G 567.7550 23.2000 S R0 - 00
IO: FILLER_S_169 PFILLER1_G 619.2600 23.2000 S R0 - 00
IO: FILLER_S_170 PFILLER1_G 620.2600 23.2000 S R0 - 00
IO: FILLER_S_171 PFILLER1_G 621.2600 23.2000 S R0 - 00
IO: FILLER_S_172 PFILLER1_G 622.2600 23.2000 S R0 - 00
IO: FILLER_S_173 PFILLER1_G 673.7650 23.2000 S R0 - 00
IO: FILLER_S_174 PFILLER1_G 674.7650 23.2000 S R0 - 00
IO: FILLER_S_175 PFILLER1_G 675.7650 23.2000 S R0 - 00
IO: FILLER_S_176 PFILLER1_G 676.7650 23.2000 S R0 - 00
IO: FILLER_S_177 PFILLER1_G 728.2700 23.2000 S R0 - 00
IO: FILLER_S_178 PFILLER1_G 729.2700 23.2000 S R0 - 00
IO: FILLER_S_179 PFILLER1_G 730.2700 23.2000 S R0 - 00
IO: FILLER_S_180 PFILLER1_G 731.2700 23.2000 S R0 - 00
IO: FILLER_S_181 PFILLER1_G 782.7800 23.2000 S R0 - 00
IO: FILLER_S_182 PFILLER1_G 783.7800 23.2000 S R0 - 00
IO: FILLER_S_183 PFILLER1_G 784.7800 23.2000 S R0 - 00
IO: FILLER_S_184 PFILLER1_G 785.7800 23.2000 S R0 - 00
IO: FILLER_S_185 PFILLER1_G 837.2900 23.2000 S R0 - 00
IO: FILLER_S_186 PFILLER1_G 838.2900 23.2000 S R0 - 00
IO: FILLER_S_187 PFILLER1_G 839.2900 23.2000 S R0 - 00
IO: FILLER_S_188 PFILLER1_G 840.2900 23.2000 S R0 - 00
IO: FILLER_S_189 PFILLER05_G 187.2000 23.2000 S R0 - 00
IO: FILLER_S_190 PFILLER05_G 241.7100 23.2000 S R0 - 00
IO: FILLER_S_191 PFILLER05_G 296.2200 23.2000 S R0 - 00
IO: FILLER_S_192 PFILLER05_G 350.7300 23.2000 S R0 - 00
IO: FILLER_S_193 PFILLER05_G 405.2400 23.2000 S R0 - 00
IO: FILLER_S_194 PFILLER05_G 459.7450 23.2000 S R0 - 00
IO: FILLER_S_195 PFILLER05_G 514.2500 23.2000 S R0 - 00
IO: FILLER_S_196 PFILLER05_G 568.7550 23.2000 S R0 - 00
IO: FILLER_S_197 PFILLER05_G 623.2600 23.2000 S R0 - 00
IO: FILLER_S_198 PFILLER05_G 677.7650 23.2000 S R0 - 00
IO: FILLER_S_199 PFILLER05_G 732.2700 23.2000 S R0 - 00
IO: FILLER_S_200 PFILLER05_G 786.7800 23.2000 S R0 - 00
IO: FILLER_S_201 PFILLER05_G 841.2900 23.2000 S R0 - 00
IO: FILLER_S_202 PFILLER0005_G 187.7000 23.2000 S R0 - 00
IO: FILLER_S_203 PFILLER0005_G 187.7050 23.2000 S R0 - 00
IO: FILLER_S_204 PFILLER0005_G 242.2100 23.2000 S R0 - 00
IO: FILLER_S_205 PFILLER0005_G 242.2150 23.2000 S R0 - 00
IO: FILLER_S_206 PFILLER0005_G 296.7200 23.2000 S R0 - 00
IO: FILLER_S_207 PFILLER0005_G 296.7250 23.2000 S R0 - 00
IO: FILLER_S_208 PFILLER0005_G 351.2300 23.2000 S R0 - 00
IO: FILLER_S_209 PFILLER0005_G 351.2350 23.2000 S R0 - 00
IO: FILLER_S_210 PFILLER0005_G 405.7400 23.2000 S R0 - 00
IO: FILLER_S_211 PFILLER0005_G 460.2450 23.2000 S R0 - 00
IO: FILLER_S_212 PFILLER0005_G 514.7500 23.2000 S R0 - 00
IO: FILLER_S_213 PFILLER0005_G 569.2550 23.2000 S R0 - 00
IO: FILLER_S_214 PFILLER0005_G 623.7600 23.2000 S R0 - 00
IO: FILLER_S_215 PFILLER0005_G 678.2650 23.2000 S R0 - 00
IO: FILLER_S_216 PFILLER0005_G 732.7700 23.2000 S R0 - 00
IO: FILLER_S_217 PFILLER0005_G 732.7750 23.2000 S R0 - 00
IO: FILLER_S_218 PFILLER0005_G 787.2800 23.2000 S R0 - 00
IO: FILLER_S_219 PFILLER0005_G 787.2850 23.2000 S R0 - 00
IO: FILLER_S_220 PFILLER0005_G 841.7900 23.2000 S R0 - 00
IO: FILLER_S_221 PFILLER0005_G 841.7950 23.2000 S R0 - 00
IO: vdd_inst3 PVDD1DGZ_G 242.2200 23.2000 S R0 - 01
IO: vss_inst3 PVSS1DGZ_G 187.7100 23.2000 S R0 - 01
IO: pwm_0 PDUW04DGZ_G 296.7300 23.2000 S R0 - 01
IO: vss_inst2 PVSS1DGZ_G 787.2900 23.2000 S R0 - 01
IO: vdd_inst2 PVDD1DGZ_G 732.7800 23.2000 S R0 - 01
IO: gpio_9 PDUW04DGZ_G 678.2700 23.2000 S R0 - 01
IO: gpio_8 PDUW04DGZ_G 623.7650 23.2000 S R0 - 01
IO: gpio_7 PDUW04DGZ_G 569.2600 23.2000 S R0 - 01
IO: gpio_6 PDUW04DGZ_G 514.7550 23.2000 S R0 - 01
IO: gpio_5 PDUW04DGZ_G 460.2500 23.2000 S R0 - 01
IO: gpio_4 PDUW04DGZ_G 405.7450 23.2000 S R0 - 01
IO: gpio_3 PDUW04DGZ_G 351.2400 23.2000 S R0 - 01
IO: p_br PCORNER_G 23.2000 23.2000 SW R0 - 00
IO: FILLER_E_0 PFILLER20_G 841.8000 158.2000 E R90 - 00
IO: FILLER_E_1 PFILLER20_G 841.8000 212.7100 E R90 - 00
IO: FILLER_E_2 PFILLER20_G 841.8000 267.2200 E R90 - 00
IO: FILLER_E_3 PFILLER20_G 841.8000 321.7300 E R90 - 00
IO: FILLER_E_4 PFILLER20_G 841.8000 376.2400 E R90 - 00
IO: FILLER_E_5 PFILLER20_G 841.8000 430.7450 E R90 - 00
IO: FILLER_E_6 PFILLER20_G 841.8000 485.2500 E R90 - 00
IO: FILLER_E_7 PFILLER20_G 841.8000 539.7550 E R90 - 00
IO: FILLER_E_8 PFILLER20_G 841.8000 594.2600 E R90 - 00
IO: FILLER_E_9 PFILLER20_G 841.8000 648.7650 E R90 - 00
IO: FILLER_E_10 PFILLER20_G 841.8000 703.2700 E R90 - 00
IO: FILLER_E_11 PFILLER20_G 841.8000 757.7800 E R90 - 00
IO: FILLER_E_12 PFILLER20_G 841.8000 812.2900 E R90 - 00
IO: FILLER_E_13 PFILLER5_G 841.8000 178.2000 E R90 - 00
IO: FILLER_E_14 PFILLER5_G 841.8000 232.7100 E R90 - 00
IO: FILLER_E_15 PFILLER5_G 841.8000 287.2200 E R90 - 00
IO: FILLER_E_16 PFILLER5_G 841.8000 341.7300 E R90 - 00
IO: FILLER_E_17 PFILLER5_G 841.8000 396.2400 E R90 - 00
IO: FILLER_E_18 PFILLER5_G 841.8000 450.7450 E R90 - 00
IO: FILLER_E_19 PFILLER5_G 841.8000 505.2500 E R90 - 00
IO: FILLER_E_20 PFILLER5_G 841.8000 559.7550 E R90 - 00
IO: FILLER_E_21 PFILLER5_G 841.8000 614.2600 E R90 - 00
IO: FILLER_E_22 PFILLER5_G 841.8000 668.7650 E R90 - 00
IO: FILLER_E_23 PFILLER5_G 841.8000 723.2700 E R90 - 00
IO: FILLER_E_24 PFILLER5_G 841.8000 777.7800 E R90 - 00
IO: FILLER_E_25 PFILLER5_G 841.8000 832.2900 E R90 - 00
IO: FILLER_E_26 PFILLER1_G 841.8000 183.2000 E R90 - 00
IO: FILLER_E_27 PFILLER1_G 841.8000 184.2000 E R90 - 00
IO: FILLER_E_28 PFILLER1_G 841.8000 185.2000 E R90 - 00
IO: FILLER_E_29 PFILLER1_G 841.8000 186.2000 E R90 - 00
IO: FILLER_E_30 PFILLER1_G 841.8000 237.7100 E R90 - 00
IO: FILLER_E_31 PFILLER1_G 841.8000 238.7100 E R90 - 00
IO: FILLER_E_32 PFILLER1_G 841.8000 239.7100 E R90 - 00
IO: FILLER_E_33 PFILLER1_G 841.8000 240.7100 E R90 - 00
IO: FILLER_E_34 PFILLER1_G 841.8000 292.2200 E R90 - 00
IO: FILLER_E_35 PFILLER1_G 841.8000 293.2200 E R90 - 00
IO: FILLER_E_36 PFILLER1_G 841.8000 294.2200 E R90 - 00
IO: FILLER_E_37 PFILLER1_G 841.8000 295.2200 E R90 - 00
IO: FILLER_E_38 PFILLER1_G 841.8000 346.7300 E R90 - 00
IO: FILLER_E_39 PFILLER1_G 841.8000 347.7300 E R90 - 00
IO: FILLER_E_40 PFILLER1_G 841.8000 348.7300 E R90 - 00
IO: FILLER_E_41 PFILLER1_G 841.8000 349.7300 E R90 - 00
IO: FILLER_E_42 PFILLER1_G 841.8000 401.2400 E R90 - 00
IO: FILLER_E_43 PFILLER1_G 841.8000 402.2400 E R90 - 00
IO: FILLER_E_44 PFILLER1_G 841.8000 403.2400 E R90 - 00
IO: FILLER_E_45 PFILLER1_G 841.8000 404.2400 E R90 - 00
IO: FILLER_E_46 PFILLER1_G 841.8000 455.7450 E R90 - 00
IO: FILLER_E_47 PFILLER1_G 841.8000 456.7450 E R90 - 00
IO: FILLER_E_48 PFILLER1_G 841.8000 457.7450 E R90 - 00
IO: FILLER_E_49 PFILLER1_G 841.8000 458.7450 E R90 - 00
IO: FILLER_E_50 PFILLER1_G 841.8000 510.2500 E R90 - 00
IO: FILLER_E_51 PFILLER1_G 841.8000 511.2500 E R90 - 00
IO: FILLER_E_52 PFILLER1_G 841.8000 512.2500 E R90 - 00
IO: FILLER_E_53 PFILLER1_G 841.8000 513.2500 E R90 - 00
IO: FILLER_E_54 PFILLER1_G 841.8000 564.7550 E R90 - 00
IO: FILLER_E_55 PFILLER1_G 841.8000 565.7550 E R90 - 00
IO: FILLER_E_56 PFILLER1_G 841.8000 566.7550 E R90 - 00
IO: FILLER_E_57 PFILLER1_G 841.8000 567.7550 E R90 - 00
IO: FILLER_E_58 PFILLER1_G 841.8000 619.2600 E R90 - 00
IO: FILLER_E_59 PFILLER1_G 841.8000 620.2600 E R90 - 00
IO: FILLER_E_60 PFILLER1_G 841.8000 621.2600 E R90 - 00
IO: FILLER_E_61 PFILLER1_G 841.8000 622.2600 E R90 - 00
IO: FILLER_E_62 PFILLER1_G 841.8000 673.7650 E R90 - 00
IO: FILLER_E_63 PFILLER1_G 841.8000 674.7650 E R90 - 00
IO: FILLER_E_64 PFILLER1_G 841.8000 675.7650 E R90 - 00
IO: FILLER_E_65 PFILLER1_G 841.8000 676.7650 E R90 - 00
IO: FILLER_E_66 PFILLER1_G 841.8000 728.2700 E R90 - 00
IO: FILLER_E_67 PFILLER1_G 841.8000 729.2700 E R90 - 00
IO: FILLER_E_68 PFILLER1_G 841.8000 730.2700 E R90 - 00
IO: FILLER_E_69 PFILLER1_G 841.8000 731.2700 E R90 - 00
IO: FILLER_E_70 PFILLER1_G 841.8000 782.7800 E R90 - 00
IO: FILLER_E_71 PFILLER1_G 841.8000 783.7800 E R90 - 00
IO: FILLER_E_72 PFILLER1_G 841.8000 784.7800 E R90 - 00
IO: FILLER_E_73 PFILLER1_G 841.8000 785.7800 E R90 - 00
IO: FILLER_E_74 PFILLER1_G 841.8000 837.2900 E R90 - 00
IO: FILLER_E_75 PFILLER1_G 841.8000 838.2900 E R90 - 00
IO: FILLER_E_76 PFILLER1_G 841.8000 839.2900 E R90 - 00
IO: FILLER_E_77 PFILLER1_G 841.8000 840.2900 E R90 - 00
IO: FILLER_E_78 PFILLER05_G 841.8000 187.2000 E R90 - 00
IO: FILLER_E_79 PFILLER05_G 841.8000 241.7100 E R90 - 00
IO: FILLER_E_80 PFILLER05_G 841.8000 296.2200 E R90 - 00
IO: FILLER_E_81 PFILLER05_G 841.8000 350.7300 E R90 - 00
IO: FILLER_E_82 PFILLER05_G 841.8000 405.2400 E R90 - 00
IO: FILLER_E_83 PFILLER05_G 841.8000 459.7450 E R90 - 00
IO: FILLER_E_84 PFILLER05_G 841.8000 514.2500 E R90 - 00
IO: FILLER_E_85 PFILLER05_G 841.8000 568.7550 E R90 - 00
IO: FILLER_E_86 PFILLER05_G 841.8000 623.2600 E R90 - 00
IO: FILLER_E_87 PFILLER05_G 841.8000 677.7650 E R90 - 00
IO: FILLER_E_88 PFILLER05_G 841.8000 732.2700 E R90 - 00
IO: FILLER_E_89 PFILLER05_G 841.8000 786.7800 E R90 - 00
IO: FILLER_E_90 PFILLER05_G 841.8000 841.2900 E R90 - 00
IO: FILLER_E_91 PFILLER0005_G 841.8000 187.7000 E R90 - 00
IO: FILLER_E_92 PFILLER0005_G 841.8000 187.7050 E R90 - 00
IO: FILLER_E_93 PFILLER0005_G 841.8000 242.2100 E R90 - 00
IO: FILLER_E_94 PFILLER0005_G 841.8000 242.2150 E R90 - 00
IO: FILLER_E_95 PFILLER0005_G 841.8000 296.7200 E R90 - 00
IO: FILLER_E_96 PFILLER0005_G 841.8000 296.7250 E R90 - 00
IO: FILLER_E_97 PFILLER0005_G 841.8000 351.2300 E R90 - 00
IO: FILLER_E_98 PFILLER0005_G 841.8000 351.2350 E R90 - 00
IO: FILLER_E_99 PFILLER0005_G 841.8000 405.7400 E R90 - 00
IO: FILLER_E_100 PFILLER0005_G 841.8000 460.2450 E R90 - 00
IO: FILLER_E_101 PFILLER0005_G 841.8000 514.7500 E R90 - 00
IO: FILLER_E_102 PFILLER0005_G 841.8000 569.2550 E R90 - 00
IO: FILLER_E_103 PFILLER0005_G 841.8000 623.7600 E R90 - 00
IO: FILLER_E_104 PFILLER0005_G 841.8000 678.2650 E R90 - 00
IO: FILLER_E_105 PFILLER0005_G 841.8000 732.7700 E R90 - 00
IO: FILLER_E_106 PFILLER0005_G 841.8000 732.7750 E R90 - 00
IO: FILLER_E_107 PFILLER0005_G 841.8000 787.2800 E R90 - 00
IO: FILLER_E_108 PFILLER0005_G 841.8000 787.2850 E R90 - 00
IO: FILLER_E_109 PFILLER0005_G 841.8000 841.7900 E R90 - 00
IO: FILLER_E_110 PFILLER0005_G 841.8000 841.7950 E R90 - 00
IO: gpio_15 PDUW04DGZ_G 841.8000 732.7800 E R90 - 01
IO: i2c_sda PDUW04DGZ_G 841.8000 678.2700 E R90 - 01
IO: i2c_scl PDUW04DGZ_G 841.8000 623.7650 E R90 - 01
IO: pwm_1 PDUW04DGZ_G 841.8000 569.2600 E R90 - 01
IO: jtag_tdo PDUW04DGZ_G 841.8000 460.2500 E R90 - 01
IO: jtag_tdi PDUW04DGZ_G 841.8000 405.7450 E R90 - 01
IO: jtag_tms PDUW04DGZ_G 841.8000 351.2400 E R90 - 01
IO: gpio_10 PDUW04DGZ_G 841.8000 296.7300 E R90 - 01
IO: vddpst_inst3 PVDD2DGZ_G 841.8000 242.2200 E R90 - 01
IO: vsspst_inst3 PVSS2DGZ_G 841.8000 187.7100 E R90 - 01
IO: vdd_inst1 PVDD1DGZ_G 841.8000 514.7550 E R90 - 01
IO: vss_inst1 PVSS1DGZ_G 841.8000 787.2900 E R90 - 01
IO: p_bl PCORNER_G 841.8000 23.2000 SE R90 - 00

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="clk_i" status="fixed" >
  </Pin>
  <Pin name="reset_i" status="fixed" >
  </Pin>
  <Pin name="uart_rx_i" status="fixed" >
  </Pin>
  <Pin name="uart_tx_o" status="fixed" >
  </Pin>
  <Pin name="spi_mosi_o" status="fixed" >
  </Pin>
  <Pin name="spi_miso_i" status="fixed" >
  </Pin>
  <Pin name="spi_sck_o" status="fixed" >
  </Pin>
  <Pin name="spi_ss_o" status="fixed" >
  </Pin>
  <Pin name="i2c_scl_io" status="fixed" >
  </Pin>
  <Pin name="i2c_sda_io" status="fixed" >
  </Pin>
  <Pin name="gpio_io[15]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[14]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[13]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[12]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[11]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[10]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[9]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[8]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[7]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[6]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[5]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[4]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[3]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[2]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[1]" status="fixed" >
  </Pin>
  <Pin name="gpio_io[0]" status="fixed" >
  </Pin>
  <Pin name="pwm0_o" status="fixed" >
  </Pin>
  <Pin name="pwm1_o" status="fixed" >
  </Pin>
  <Pin name="jtag_tck_i" status="fixed" >
  </Pin>
  <Pin name="jtag_tms_i" status="fixed" >
  </Pin>
  <Pin name="jtag_tdi_i" status="fixed" >
  </Pin>
  <Pin name="jtag_tdo_o" status="fixed" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="top">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
