#!/usr/bin/env python3
"""Walk a directory tree and emit a cpio_list spec for gen_init_cpio.

The output is the input format for the kernel's usr/gen_init_cpio tool —
which can produce an initramfs.cpio that includes character/block device
nodes (e.g. /dev/console) WITHOUT needing root, unlike `find | cpio -o`.

Default behaviour also injects /dev/console (c 5 1) and /dev/null (c 1 3)
because they're required for kernel init to attach to the console.
"""
import argparse
import os
import stat
import sys


def emit(line):
    sys.stdout.write(line + "\n")


def walk(root, prefix=""):
    entries = sorted(os.listdir(root))
    for name in entries:
        full = os.path.join(root, name)
        rel = prefix + "/" + name
        st = os.lstat(full)
        mode_oct = oct(st.st_mode & 0o7777)[2:]
        uid = 0   # always root in cpio
        gid = 0
        if stat.S_ISDIR(st.st_mode):
            emit(f"dir {rel} {mode_oct} {uid} {gid}")
            walk(full, rel)
        elif stat.S_ISLNK(st.st_mode):
            target = os.readlink(full)
            emit(f"slink {rel} {target} {mode_oct} {uid} {gid}")
        elif stat.S_ISREG(st.st_mode):
            emit(f"file {rel} {full} {mode_oct} {uid} {gid}")
        elif stat.S_ISCHR(st.st_mode):
            major = os.major(st.st_rdev)
            minor = os.minor(st.st_rdev)
            emit(f"nod {rel} {mode_oct} {uid} {gid} c {major} {minor}")
        elif stat.S_ISBLK(st.st_mode):
            major = os.major(st.st_rdev)
            minor = os.minor(st.st_rdev)
            emit(f"nod {rel} {mode_oct} {uid} {gid} b {major} {minor}")
        elif stat.S_ISFIFO(st.st_mode):
            emit(f"pipe {rel} {mode_oct} {uid} {gid}")
        else:
            print(f"# WARN: skipping {rel} (unknown type)", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root", help="root of the unpacked initramfs tree")
    ap.add_argument("--no-default-devs", action="store_true",
                    help="don't auto-inject /dev/console + /dev/null")
    args = ap.parse_args()

    # Top-level "/" is implicit in cpio; gen_init_cpio doesn't want a
    # `dir /` entry. Walk the tree.
    emit(f"# Generated by dir_to_cpio_list.py from {args.root}")
    walk(args.root, "")

    if not args.no_default_devs:
        # Required device nodes that cpio extraction (as non-root) drops.
        # Kernel init opens /dev/console before devtmpfs is mounted.
        # /dev/null exists for sanity (some early scripts redirect to it).
        emit("# Required device nodes (auto-injected; not present in source tree)")
        emit("nod /dev/console 600 0 0 c 5 1")
        emit("nod /dev/null    666 0 0 c 1 3")


if __name__ == "__main__":
    main()
