#!/usr/bin/env python3
"""Generate memory map files from design/common/mem_map.json.

Outputs:
  design/common/mem_map.svh          — SystemVerilog `define header
  design/common/mem_map.h            — C header (NTINY_ prefixed)
  software/common/link.ld                  — linker script (default profile)
  verification/riscof/ntiny/env/link.ld    — linker script (riscof profile)

Usage:
  python3 scripts/gen_mem_map.py              # from repo root
  python3 scripts/gen_mem_map.py --check      # verify generated files are up-to-date
"""

import json
import os
import sys
import argparse

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
JSON_PATH = os.path.join(REPO_ROOT, "design", "common", "mem_map.json")

BANNER = "// AUTO-GENERATED by scripts/gen_mem_map.py — DO NOT EDIT\n// Source: design/common/mem_map.json\n"
C_BANNER = BANNER.replace("//", "//")


def load_json():
    with open(JSON_PATH) as f:
        return json.load(f)


def hex32(val):
    """Convert hex-string or int to 0x prefixed 8-digit uppercase hex."""
    if isinstance(val, str):
        val = int(val, 16)
    return f"0x{val:08X}"


def sv_hex32(val):
    """SV-style 32'hXXXX_XXXX."""
    if isinstance(val, str):
        val = int(val, 16)
    h = f"{val:08X}"
    return f"32'h{h[0:4]}_{h[4:8]}"


def gen_svh(data):
    """Generate mem_map.svh content."""
    lines = [BANNER, ""]
    default = data["profiles"]["default"]

    # Overridable memory regions (ifndef guards)
    for region in ["RAM", "BOOT"]:
        base_key = f"{region}_BASE"
        size_key = f"{region}_SIZE_BYTES"
        lines.append(f"// --- {region} ---")
        lines.append(f"`ifndef {base_key}")
        lines.append(f"  `define {base_key}     {sv_hex32(default[base_key])}")
        lines.append(f"`endif")
        lines.append(f"`ifndef {size_key}")
        lines.append(f"  `define {size_key} {sv_hex32(default[size_key])}")
        lines.append(f"`endif")
        lines.append(f"`define {region}_END        (`{base_key} + `{size_key} - 1)")
        lines.append(f"`define {region}_DEPTH      (`{size_key} / 4)")
        lines.append(f"`define {region}_ADDR_WIDTH $clog2(`{region}_DEPTH)")
        lines.append("")

    # Peripherals (fixed addresses, no guards)
    lines.append("// --- Peripherals ---")
    for name, info in data["peripherals"].items():
        lines.append(f"`define {name}_BASE        {sv_hex32(info['base'])}")
        lines.append(f"`define {name}_END         {sv_hex32(info['end'])}")
    lines.append("")

    # Special addresses
    lines.append("// --- Special ---")
    for name, addr in data["special"].items():
        lines.append(f"`define {name}     {sv_hex32(addr)}")
    lines.append("")

    return "\n".join(lines)


def gen_c_header(data):
    """Generate mem_map.h content."""
    lines = [
        BANNER,
        "",
        "#ifndef NTINY_MEM_MAP_H",
        "#define NTINY_MEM_MAP_H",
        "",
    ]
    default = data["profiles"]["default"]

    for region in ["RAM", "BOOT"]:
        base_key = f"{region}_BASE"
        size_key = f"{region}_SIZE_BYTES"
        lines.append(f"#define NTINY_{base_key}       {hex32(default[base_key])}")
        lines.append(f"#define NTINY_{size_key}  {hex32(default[size_key])}")
    lines.append("")

    lines.append("// Peripherals")
    for name, info in data["peripherals"].items():
        lines.append(f"#define NTINY_{name}_BASE      {hex32(info['base'])}")
    lines.append("")

    lines.append("// Special")
    for name, addr in data["special"].items():
        lines.append(f"#define NTINY_{name}   {hex32(addr)}")
    lines.append("")

    # Backward-compatible aliases (existing code uses e.g. UART_BASE_ADDR)
    aliases = {
        "UART_BASE_ADDR":  "NTINY_UART_BASE",
        "TIMER_BASE_ADDR": "NTINY_TIMER_BASE",
        "GPIO_BASE_ADDR":  "NTINY_GPIO_BASE",
        "PLIC_BASE_ADDR":  "NTINY_PLIC_BASE",
        "SPI_BASE_ADDR":   "NTINY_SPI_BASE",
        "BASE_ADDR":       "NTINY_I2C_BASE",     # i2c_defs.h uses BASE_ADDR
        "pwm_base_addr":   "NTINY_PWM_BASE",
    }
    lines.append("// Backward-compatible aliases")
    for old, new in aliases.items():
        lines.append(f"#ifndef {old}")
        lines.append(f"  #define {old}  {new}")
        lines.append(f"#endif")
    lines.append("")

    lines.append("#endif // NTINY_MEM_MAP_H")
    lines.append("")
    return "\n".join(lines)


def gen_linker_script(data, profile_name):
    """Generate a linker script for the given profile."""
    profile = data["profiles"][profile_name]

    ram_base  = hex32(profile["RAM_BASE"])
    ram_size  = hex32(profile["RAM_SIZE_BYTES"])
    tohost    = hex32(data["special"]["TOHOST_ADDR"])

    if profile_name == "default":
        return gen_default_linker(ram_base, ram_size, tohost)
    elif profile_name == "riscof":
        return gen_riscof_linker(ram_base, ram_size, tohost)
    else:
        raise ValueError(f"Unknown profile: {profile_name}")


def gen_default_linker(ram_base, ram_size, tohost):
    """Default linker script for bare-metal software."""
    return f"""\
/* AUTO-GENERATED by scripts/gen_mem_map.py — DO NOT EDIT */
/* Source: design/common/mem_map.json (profile: default) */
OUTPUT_FORMAT("elf32-littleriscv", "elf32-littleriscv", "elf32-littleriscv")
GROUP(-lc -lgloss -lgcc -lm)
OUTPUT_ARCH(riscv)

MEMORY
{{
  RAM (rwx) : ORIGIN = {ram_base}, LENGTH = {ram_size}
}}

ENTRY(_init)

SECTIONS
{{
  PROVIDE(__stack_top = ORIGIN(RAM) + LENGTH(RAM));

  .init           : {{ *(.init) }} > RAM
  .RESET_HANDLER  : {{ *(.RESET_HANDLER) }} > RAM
  .ISR_SOFT_ASM   : {{ *(.ISR_SOFT_ASM) }} > RAM
  .ISR_TIMER_ASM  : {{ *(.ISR_TIMER_ASM) }} > RAM
  .ISR_EXT_ASM    : {{ *(.ISR_EXT_ASM) }} > RAM
  .ISR_DEFAULT_ASM : {{ *(.ISR_DEFAULT_ASM) }} > RAM
  .text :
  {{
    *(.text.unlikely .text.*_unlikely .text.unlikely.*)
    *(.text.exit .text.exit.*)
    *(.text.startup .text.startup.*)
    *(.text.hot .text.hot.*)
    *(SORT(.text.sorted.*))
    *(.text .stub .text.* .gnu.linkonce.t.*)
    *(.gnu.warning)
  }} > RAM
  PROVIDE (__etext = .);
  PROVIDE (_etext = .);
  PROVIDE (etext = .);

  .rodata : {{ *(.rodata .rodata.* .gnu.linkonce.r.*) }} > RAM
  .data :
  {{
    __DATA_BEGIN__ = .;
    *(.data .data.* .gnu.linkonce.d.*)
    SORT(CONSTRUCTORS)
    __SDATA_BEGIN__ = .;
    *(.srodata.cst16) *(.srodata.cst8) *(.srodata.cst4) *(.srodata.cst2) *(.srodata .srodata.*)
    *(.sdata .sdata.* .gnu.linkonce.s.*)
  }} > RAM

  _edata = .; PROVIDE (edata = .);
  . = .;
  __bss_start = .;

  .sbss :
  {{
    *(.dynsbss)
    *(.sbss .sbss.* .gnu.linkonce.sb.*)
    *(.scommon)
  }} > RAM
  .bss :
  {{
    *(.dynbss)
    *(.bss .bss.* .gnu.linkonce.b.*)
    *(COMMON)
    . = ALIGN(. != 0 ? 32 / 8 : 1);
  }} > RAM

  . = ALIGN(32 / 8);
  . = SEGMENT_START("ldata-segment", .);
  . = ALIGN(32 / 8);
  __BSS_END__ = .;
  __global_pointer$ = MIN(__SDATA_BEGIN__ + 0x800,
                      MAX(__DATA_BEGIN__ + 0x800, __BSS_END__ - 0x800));

  /* tohost at fixed bus address */
  .tohost {tohost} (NOLOAD) : {{ *(.tohost) }}

  _end = .; PROVIDE (end = .);
}}
"""


def gen_riscof_linker(ram_base, ram_size, tohost):
    """RISCOF compliance linker script — unified RAM.

    The section layout intentionally mirrors spike's reference linker
    (verification/riscof/spike/env/link.ld) so that GCC produces
    BIT-IDENTICAL .text/.data section addresses for both binaries:

       .text.init -> 1-page gap -> 1-page gap -> .text -> 1-page gap -> .data

    spike's linker reserves a 1-page slot between .text.init and .text
    for its in-RAM .tohost section. ntiny puts .tohost at a fixed
    bus-monitored address (0x0F000000) outside RAM, so it doesn't need
    the slot — but if we omit it, .text and .data shift DOWN by 0x1000
    relative to spike's binary. Test code that uses absolute PC values
    (e.g. AUIPC + signature writes of EPCs) then diverges from the
    reference signature, causing dozens of false-positive RISCOF
    failures across the PMP / vm_sv32 / privilege suites.

    Reserve an explicit 1-page placeholder so the alignment matches.
    """
    return f"""\
/* AUTO-GENERATED by scripts/gen_mem_map.py — DO NOT EDIT */
/* Source: design/common/mem_map.json (profile: riscof) */
OUTPUT_ARCH( "riscv" )
ENTRY(rvtest_entry_point)

MEMORY
{{
  RAM (rwx) : ORIGIN = {ram_base}, LENGTH = {ram_size}
}}

SECTIONS
{{
  .text.init : {{ *(.text.init) }} > RAM

  /* Reserve a NOBITS 1-page slot to match spike's layout. spike's
     reference linker puts a real .tohost section in RAM between
     .text.init and .data, so .data lands at .text.init_end + 2 pages.
     ntiny puts .tohost at a fixed bus-monitored address outside RAM,
     so it doesn't need a backing slot — but if we don't reserve one,
     .data ends up at .text.init_end + 1 page, shifted DOWN by 0x1000
     relative to spike's binary. Tests that use absolute PC values
     (AUIPC + signature writes of EPCs) then diverge from the spike
     reference signature, causing dozens of false-positive RISCOF
     failures across the PMP / vm_sv32 / privilege suites. */
  . = ALIGN(0x1000);
  .tohost_pad (NOLOAD) : {{ . = . + 0x1000; }} > RAM

  . = ALIGN(0x1000);
  .text : {{ *(.text) }} > RAM

  . = ALIGN(0x1000);
  .data : {{ *(.data) *(.data.*) *(.data.string) }} > RAM
  .sdata : {{ *(.sdata) *(.sdata.*) }} > RAM
  .bss (NOLOAD) : {{ *(.bss) *(.bss.*) }} > RAM

  /* tohost at fixed bus address — no backing memory needed, testbench monitors bus writes */
  .tohost {tohost} (NOLOAD) : {{ *(.tohost) }}

  _end = .;
}}
"""


def write_if_changed(path, content):
    """Write file only if content differs. Returns True if written."""
    abs_path = os.path.join(REPO_ROOT, path)
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)
    try:
        with open(abs_path) as f:
            if f.read() == content:
                return False
    except FileNotFoundError:
        pass
    with open(abs_path, "w") as f:
        f.write(content)
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate memory map files from mem_map.json")
    parser.add_argument("--check", action="store_true",
                        help="Check if generated files are up-to-date (exit 1 if stale)")
    args = parser.parse_args()

    data = load_json()

    outputs = {
        "design/common/mem_map.svh":
            gen_svh(data),
        "design/common/mem_map.h":
            gen_c_header(data),
        "software/common/link.ld":
            gen_linker_script(data, "default"),
        "verification/riscof/ntiny/env/link.ld":
            gen_linker_script(data, "riscof"),
    }

    if args.check:
        stale = []
        for path, content in outputs.items():
            abs_path = os.path.join(REPO_ROOT, path)
            try:
                with open(abs_path) as f:
                    if f.read() != content:
                        stale.append(path)
            except FileNotFoundError:
                stale.append(path)
        if stale:
            print("ERROR: Generated files are stale. Run: python3 scripts/gen_mem_map.py")
            for p in stale:
                print(f"  {p}")
            sys.exit(1)
        else:
            print("OK: All generated files are up-to-date.")
            sys.exit(0)

    wrote = 0
    for path, content in outputs.items():
        if write_if_changed(path, content):
            print(f"  wrote {path}")
            wrote += 1
        else:
            print(f"  unchanged {path}")
    print(f"Done. {wrote}/{len(outputs)} files updated.")


if __name__ == "__main__":
    main()
